name: Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.timolia.de/web/howto"
      env:
        FORCE_PUSH: "true"
        GITLAB_HOSTNAME: "gitlab.timolia.de"
        GITLAB_USERNAME: "github-mirror"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "130"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
